apiVersion: v1
kind: Service
metadata:
  name: kafka-consumer
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8081
    name: http
  - port: 443
    protocol: TCP
    targetPort: 8081
    name: https
  selector:
    app: kafka-consumer